server:
  error:
    whitelabel:
      enabled: true
  servlet:
    context-path: /api

spring:
  profiles:
    active: @activatedProperties@
  application:
    name: @project.name@_${spring.profiles.active}


